// import { collection } from "../../../models/category.model";

export let entities = [
  { displayName: "DashBoard" },
  {
    displayName: "Categories",
    dbCollection: "categories",
    btnLabel: "Category",
    requiredLists: [],
    attributes: [
      {
        id: "name",
        label: "Name",
        type: "text",
        placeholder: "Enter category name",
        value: "",
      },
      {
        id: "image",
        label: "Image",
        type: "text",
        placeholder: "Enter image name",
        value: "",
      },
    ],
  },
  {
    displayName: "Products",
    dbCollection: "products",
    btnLabel: "Product",
    requiredLists: [{ dbRoute: "categories", listName: "categoryList" }],
    attributes: [
      {
        id: "name",
        label: "Name",
        type: "text",
        placeholder: "Enter product name",
        value: "",
      },
      {
        id: "price",
        label: "Price",
        type: "number",
        placeholder: "Enter product price",
        value: "",
      },
      {
        id: "isAvailable",
        label: "Available",
        // type: "checkbox",
        type: "radio",
        options: ["Yes", "No"],
        value: "db.products",
      },
      {
        id: "categoryId",
        label: "Category",
        type: "dropdown",
        options: "categoryList",
        value: "",
      },
    ],
  },
  {
    displayName: "Samples",
    dbCollection: "products",
    btnLabel: "Product",
    attributes: [
      {
        id: "name",
        label: "Product Name",
        type: "text",
        placeholder: "Enter product name",
        value: "",
      },
      {
        id: "price",
        label: "Price",
        type: "number",
        placeholder: "Enter product price",
        value: "",
      },
      {
        id: "category",
        label: "Category",
        type: "text",
        placeholder: "Enter product category",
        value: "",
      },
      {
        id: "isAvailable",
        label: "Available",
        // type: "checkbox",
        type: "radio",
        options: ["Yes", "No"],
        value: "Yes",
      },
      {
        id: "shippingMethod",
        label: "Shipping Method",
        type: "radio",
        options: ["Standard", "Express"],
        value: "",
      },
      {
        id: "brand",
        label: "Region",
        type: "dropdown",
        options: ["Kashmir", "Maharashtra", "Imported", "Kerla"],
        value: "",
      },
      {
        id: "features",
        label: "Fruit Type",
        type: "checkbox-group",
        options: ["Organic", "NON-organic", "hybrid"],
        value: [],
      },
      {
        id: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter product description",
        value: "",
      },
    ],
  },
  { displayName: "Tables" },
  { displayName: "Staff" },
  { displayName: "POS" },
  { displayName: "Kitchen" },
  { displayName: "Reports" },
  { displayName: "Settings" },
];
