export let entities = [
  {
    displayName: "Customers",
    dbCollection: "customers",
    btnLabel: "Customer",
    requiredLists: [],
    attributes: [
      {
        id: "name",
        label: "Name",
        type: "text",
        placeholder: "Enter customer name",
        value: "",
        validations: { message: "", mxLen: 80, mnLen: 3, onlyDigits: false },
      },
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        placeholder: "Enter company name",
        value: "",
        validations: { message: "", mxLen: 80, mnLen: 3, onlyDigits: false },
      },
      {
        id: "mobileNumber",
        label: "Mobile Number",
        type: "text",
        placeholder: "Enter Mobile Number",
        value: "",
        validations: {
          message: "",
          mxLen: 10,
          mnLen: 10,
          onlyDigits: true,
        },
      },
      {
        id: "emailId",
        label: "Email-id",
        type: "text",
        placeholder: "Enter Email-id",
        value: "",
        validations: { message: "", mxLen: 80, mnLen: 3, onlyDigits: false },
      },
      {
        id: "address",
        label: "Address-id",
        type: "text",
        placeholder: "Enter Address",
        value: "",
        validations: { message: "", mxLen: 80, mnLen: 3, onlyDigits: false },
      },
    ],
  },
  {
    displayName: "Products",
    dbCollection: "products",
    btnLabel: "Product",
    // requiredLists: [{ dbRoute: "categories", listName: "categoryList" }],
    requiredLists: [],
    attributes: [
      {
        id: "name",
        label: "Name",
        type: "text",
        placeholder: "Enter product name",
        value: "",
        validations: { message: "", mxLen: 80, mnLen: 3, onlyDigits: false },
      },
      {
        id: "price",
        label: "Price",
        type: "number",
        placeholder: "Enter product price",
        value: "",
        validations: { message: "", mxLen: 80, mnLen: 3, onlyDigits: false },
      },
      {
        id: "isAvailable",
        label: "Available",
        type: "radio",
        options: ["Yes", "No"],
        value: "No",
        validations: { message: "", mxLen: 80, mnLen: 3, onlyDigits: false },
      },
      {
        id: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter product details",
        value: "",
        validations: { message: "", mxLen: 80, mnLen: 10, onlyDigits: false },
      },
      {
        id: "image",
        label: "Image",
        type: "file",
        // placeholder: "Upload image file",
        value: "",
        preview: "",
        file: "",
        tempFile: "", // while editing, this is the new file
        validations: { message: "", mxLen: 80, mnLen: 10, onlyDigits: false },
      },
      // {
      //   id: "categoryId",
      //   label: "Category",
      //   type: "dropdown",
      //   options: "categoryList",
      //   value: "Category A",
      // },
    ],
  },
  {
    displayName: "Samples",
    dbCollection: "products",
    btnLabel: "Product",
    attributes: [
      {
        id: "name",
        label: "Product Name",
        type: "text",
        placeholder: "Enter product name",
        value: "kaka mala wachwa",
      },
      {
        id: "price",
        label: "Price",
        type: "number",
        placeholder: "Enter product price",
        value: "",
      },
      {
        id: "category",
        label: "Category",
        type: "text",
        placeholder: "Enter product category",
        value: "",
      },
      {
        id: "isAvailable",
        label: "Available",
        // type: "checkbox",
        type: "radio",
        options: ["Yes", "No"],
        value: "No",
      },
      {
        id: "shippingMethod",
        label: "Shipping Method",
        type: "radio",
        options: ["Standard", "Express"],
        value: "",
      },
      {
        id: "brand",
        label: "Region",
        type: "dropdown",
        options: ["Kashmir", "Maharashtra", "Imported", "Kerla"],
        value: "",
      },
      {
        id: "features",
        label: "Fruit Type",
        type: "checkbox-group",
        options: ["Organic", "NON-organic", "hybrid"],
        value: [],
      },
      {
        id: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter product description",
        value: "",
      },
    ],
  },
  { displayName: "Tables" },
  { displayName: "Staff" },
  { displayName: "POS" },
  { displayName: "Kitchen" },
  { displayName: "Reports" },
  { displayName: "Settings" },
];
